name: Build Fat Jar

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file DBDKairyu/pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DBD-Tool-FatJar
        path: DBDKairyuu/target/*-shaded.jar

